apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: bitcoinjs-guide
  namespace: openfaas
spec:
  domain: "bitcoinjs-guide.rogue-paprika.top"
  function: "bitcoinjs-guide"
  ingressType: "nginx"
  tls:
    enabled: true
    issuerRef:
      name: "letsencrypt-staging"
      kind: "Issuer"
